set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -R
bind-key u select-pane -U

bind-key e split-window -h
bind-key E split-window -v
unbind-key t
bind-key t new-window
bind-key R command-prompt -I "#W" "rename-window '%%'"

set -g mouse on
set -g set-clipboard on
set-window-option -g xterm-keys on
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

set-option -g status-position top

set-option -g default-shell /bin/zsh

# command delay? We don't want that, make it short
set -g escape-time 10

# Allow the arrow key to be used immediately after changing windows
set-option -g repeat-time 0

# Set window notifications
set -g monitor-activity on
set -g visual-activity on

# Reduce time to wait for Escape key. You'll want this for neovim.
set-option escape-time 40

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tpm-sensible'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_flavour 'mocha'

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_background "#{thm_gray}"
set -g @catppuccin_status_background "default"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory session"
set -g @catppuccin_status_left_separator " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run '~/.tmux/plugins/tpm/tpm'
run '~/.local/share/tmux/plugins/tpm/tpm'
