# # ~/.config/starship.toml

# # Inserts a blank line between shell prompts
# add_newline = true

# # Change command timeout from 500 to 1000 ms
# command_timeout = 1000

# # new config
# format = """$env_var $all"""

# Change the default prompt characters
[character]
success_symbol = ""
error_symbol = ""

disabled = false

# Shows the username
[username]
style_user = "bold blue"
style_root = "white"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = true
ssh_symbol = " "
format = "on [$hostname](bold yellow) "
disabled = false

[directory]
truncation_length = 1
home_symbol = "  ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "󰊢 "
format = "via [$symbol$branch]($style) "
# truncation_length = 4
style = "#ff9800"
disabled = false

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "
disabled = true

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"
format = "([+$added]($added_style))( [-$deleted]($deleted_style) )"

# [kubernetes]
# format = 'via [󰠳 $context\($namespace\)](bold purple) '
# disabled = true

# # (deactivated because of no space left)
# # 
# # [terraform]
# # format = "via [ terraform $version]($style) 壟 [$workspace]($style) "
# # disabled = true

[docker_context]
format = "via [󰡨 $context](bold blue) "
disabled = true

[dotnet]
disabled = false
symbol = ".NET "

# [helm]
# format = "via [󰠳 $version](bold purple) "
# disabled = true

[nodejs]
format = "via [󰎙 $version](bold green) "
disabled = false

[aws]
symbol = "  "

[buf]
disabled = true

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[scala]
symbol = " "
